---
title: "Appendix S4: Testing for generality of pollinator recognition in *Heliconia* - Testing for mechanisms"
author: "D. G. Gannon, A. S. Hadley, U. G. Kormann, F. A. Jones, and M. G. Betts"
output:
  github_document:
    pandoc_args: --webtex
header-includes:
  \usepackage{setspace}
  \onehalfspacing
  \usepackage{bm}
bibliography: /Users/dusty/Documents/zotero_library.bib
---


```{r fig 3 main text, echo=FALSE, eval=FALSE}

  X <- mod.data[["X"]]
  beta_post <- as.matrix(as.data.frame(extract(mfit, pars="beta")))
  
# create vectors for linear predictors
  hpros <- as.double(X[which(nectar$Species == "H.rostrata" & 
                               nectar$f.trt == "HP")[1], ])
  bmros <- as.double(X[which(nectar$Species == "H.rostrata" & 
                               nectar$f.trt == "PM")[1], ])
  hpneros <- as.double(X[which(nectar$Species == "H.rostrata" & 
                               nectar$f.trt == "HPNE")[1], ])
  nehpros <- as.double(X[which(nectar$Species == "H.rostrata" & 
                               nectar$f.trt == "NEHP")[1], ])
  hptor <- as.double(X[which(nectar$Species == "H.tortuosa" & 
                               nectar$f.trt == "HP")[1], ])
  bmtor <- as.double(X[which(nectar$Species == "H.tortuosa" & 
                               nectar$f.trt == "PM")[1], ])
  hpnetor <- as.double(X[which(nectar$Species == "H.tortuosa" & 
                               nectar$f.trt == "HPNE")[1], ])
  nehptor <- as.double(X[which(nectar$Species == "H.tortuosa" & 
                               nectar$f.trt == "NEHP")[1], ])
  hpwag <- as.double(X[which(nectar$Species == "H.wagneriana" & 
                               nectar$f.trt == "HP")[1], ])
  bmwag <- as.double(X[which(nectar$Species == "H.wagneriana" & 
                               nectar$f.trt == "PM")[1], ])
  hpnewag <- as.double(X[which(nectar$Species == "H.wagneriana" & 
                               nectar$f.trt == "HPNE")[1], ])
  nehpwag <- as.double(X[which(nectar$Species == "H.wagneriana" & 
                               nectar$f.trt == "NEHP")[1], ])

  
# Create posterior means and CIs
  species <- rep(c("H. rostrata", "H. tortuosa", "H. wagneriana"), each=4)
  trt <- rep(c("HP", "HP + \npipette", "HP + \nnectar \nextraction", "Nectar \nextraction + \nHP"), 3)
  X.unique <- rbind(hpros, bmros, hpneros, nehpros,
                    hptor, bmtor, hpnetor, nehptor,
                    hpwag, bmwag, hpnewag, nehpwag)
  
  loglambda_post <- beta_post%*%t(X.unique)
  lambda_post <- apply(loglambda_post, 2, exp)
  
  df.plot <- data.frame(species=species, trt=trt,
                          estim=apply(lambda_post, 2, mean),
                          low=apply(lambda_post,2,quantile, probs=0.025),
                          medlow=apply(lambda_post,2,quantile, probs=0.1),
                          medhigh=apply(lambda_post,2,quantile, probs=0.9),
                          high=apply(lambda_post,2,quantile, probs=0.975))
  df.plot$trt <- factor(df.plot$trt, 
                        levels = c("HP", "HP + \npipette", "HP + \nnectar \nextraction", "Nectar \nextraction + \nHP"))
  
  plottheme <- theme(panel.background = element_blank(),
                     axis.line = element_line(colour = "black"),
                     plot.title = element_text(face="italic", size = 16),
                     axis.text = element_text(colour = "black", size = 12),
                     axis.title = element_text(size = 16))
  
  xtitle <- textGrob("Pollen tubes per style", rot = 90, gp=gpar(fontsize=20))
  
  ros <- ggplot(data = df.plot[1:4,], aes(x=trt, y=estim))+
    geom_errorbar(ymin=df.plot$low[1:4], ymax=df.plot$high[1:4], width=0)+
    geom_errorbar(ymin=df.plot$medlow[1:4], ymax=df.plot$medhigh[1:4], width=0, size=1.2)+
    geom_point(size=3.5, color="white")+
    geom_point(size=3)+
    ylim(c(0,1.5))+
    plottheme +
    theme(axis.text.x = element_text(colour = "white"))+
    ylab("")+
    xlab("")+
    ggtitle("H. rostrata")
  
  tor <- ggplot(data = df.plot[5:8,], aes(x=trt, y=estim))+
    geom_errorbar(ymin=df.plot$low[5:8], ymax=df.plot$high[5:8], width=0)+
    geom_errorbar(ymin=df.plot$medlow[5:8], ymax=df.plot$medhigh[5:8], width=0, size=1.2)+
    geom_point(size=3.5, color="white")+
    geom_point(size=3)+
    ylim(c(0,1.5))+
    plottheme +
    theme(axis.text.x = element_text(colour = "white"))+
    ylab("")+
    xlab("")+
    ggtitle("H. tortuosa")
  
  wag <- ggplot(data = df.plot[9:12,], aes(x=trt, y=estim))+
    geom_errorbar(ymin=df.plot$low[9:12], ymax=df.plot$high[9:12], width=0)+
    geom_errorbar(ymin=df.plot$medlow[9:12], ymax=df.plot$medhigh[9:12], width=0, size=1.2)+
    geom_point(size=3.5, color="white")+
    geom_point(size=3)+
    ylim(c(0,3.5))+
    plottheme +
    ylab("")+
    xlab("")+
    ggtitle("H. wagneriana")+
    scale_y_continuous(breaks=c(0,1,2,3), labels = c("0.0", "1.0", "2.0", "3.0"), 
                       limits = c(0,3.5))
  
  lo <- rbind(c(1,2,2,2,2,2),
              c(1,3,3,3,3,3),
              c(1,4,4,4,4,4))
  
png(filename = "~/Documents/Heliconia/Analyses/PR/PR_HPvsHPNE_short/figure_3_means_plot.png", width = 1800, height = 3000,
      res = 300)
  grid.arrange(xtitle, ros, tor, wag, layout_matrix=lo)
dev.off()

```


```{r eval=FALSE, echo=FALSE}

  beta_post_full <- as.matrix(as.data.frame(extract(mfit, pars="beta")))
  X <- mod.data[["X"]]

  hpros_full <- as.double(X[which(nectar$Species == "H.rostrata" & 
                               nectar$f.trt == "HP")[1], ])
  nehpros_full <- as.double(X[which(nectar$Species == "H.rostrata" & 
                               nectar$f.trt == "NEHP")[1], ])
  hptor_full <- as.double(X[which(nectar$Species == "H.tortuosa" & 
                               nectar$f.trt == "HP")[1], ])
  nehptor_full <- as.double(X[which(nectar$Species == "H.tortuosa" & 
                               nectar$f.trt == "NEHP")[1], ])
  hpwag_full <- as.double(X[which(nectar$Species == "H.wagneriana" &
                                    nectar$f.trt == "HP")[1], ])
  nehpwag_full <- as.double(X[which(nectar$Species == "H.wagneriana" & 
                               nectar$f.trt == "NEHP")[1], ])
# H. rostrata
  mean(exp(as.double(beta_post_full%*%nehpros_full) - 
             as.double(beta_post_full%*%hpros_full)))
  quantile(exp(as.double(beta_post_full%*%nehpros_full) - 
             as.double(beta_post_full%*%hpros_full)), probs = c(0.025,0.975))
  
# H. tortuosa
  mean(exp(as.double(beta_post_full%*%nehptor_full) - 
             as.double(beta_post_full%*%hptor_full)))
  quantile(exp(as.double(beta_post_full%*%nehptor_full) - 
             as.double(beta_post_full%*%hptor_full)), probs = c(0.025,0.975)) 
  
 # H. wagneriana
  mean(exp(as.double(beta_post_full%*%nehpwag_full) - 
             as.double(beta_post_full%*%hpwag_full)))
  quantile(exp(as.double(beta_post_full%*%nehpwag_full) - 
             as.double(beta_post_full%*%hpwag_full)), probs = c(0.025,0.975))  

```
